apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dra-cpu-driver-role
  namespace: openshift-cluster-node-tuning-operator
rules:
- apiGroups: ["resource.k8s.io"]
  resources: ["resourceclaims"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
- apiGroups: ["resource.k8s.io"]
  resources: ["resourceslices"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

