apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dra-cpu-driver-kubeletplugin
  labels:
    app.kubernetes.io/name: dra-cpu-driver
    app.kubernetes.io/instance: dra-cpu-driver
    app.kubernetes.io/version: "0.1.0"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dra-cpu-driver
      app.kubernetes.io/instance: dra-cpu-driver
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dra-cpu-driver
        app.kubernetes.io/instance: dra-cpu-driver
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: dra-cpu-driver-service-account
      containers:
      - name: plugin
        securityContext:
          privileged: true
        image: quay.io/titzhak/dra-cpu-driver:latest
        imagePullPolicy: Always
        command: ["dra-cpu-kubeletplugin"]
        args:
          - --reserved-cpus=0,1
          - --allocatable-cpus=3-7
          - --shared-cpus=2
        env:
        - name: CDI_ROOT
          value: /var/run/cdi
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NUM_DEVICES
          value: "8"
        volumeMounts:
        - name: plugins-registry
          mountPath: /var/lib/kubelet/plugins_registry
        - name: plugins
          mountPath: /var/lib/kubelet/plugins
        - name: cdi
          mountPath: /var/run/cdi
      volumes:
      - name: plugins-registry
        hostPath:
          path: /var/lib/kubelet/plugins_registry
      - name: plugins
        hostPath:
          path: /var/lib/kubelet/plugins
      - name: cdi
        hostPath:
          path: /var/run/cdi

