apiVersion: resource.k8s.io/v1beta1
kind: DeviceClass
metadata:
  name: exclusive-cpu
spec:
  selectors:
    - cel:
        expression: device.driver == "manager.cpu.com" && device.attributes["manager.cpu.com"].allocatable == true
---
apiVersion: resource.k8s.io/v1beta1
kind: DeviceClass
metadata:
  name: shared-cpu
spec:
  selectors:
    - cel:
        expression: device.driver == "manager.cpu.com" && device.attributes["manager.cpu.com"].shared == true

