apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: dra-cpu-driver-scc
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowHostIPC: false
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
- hostPath
- secret
- configMap
- emptyDir

